name: Deploy

on:
  push:
    branches:
      - production
      - main
  workflow_dispatch:

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/production' && 'prod' || 'dev' }}
  REGION: eastus

jobs:
  build-interaction-gateway:
    name: Build and test interaction gateway
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "InteractionGateway"
    defaults:
      run:
        working-directory: ./${{ env.PROJECT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: ${{ env.PROJECT_NAME }}
          sparse-checkout-cone-mode: false

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Test project
        run: |
          dotnet test --configuration Release

      - name: Create zip and prepare for deployment
        run: |
          dotnet publish --configuration Release --output ./output --self-contained
          pushd ./output
          zip -r ../../${{ env.PROJECT_NAME }}.zip .
          popd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ github.sha }}
          path: ./${{ env.PROJECT_NAME }}.zip

  # TODO: Add deployment job - pull in zip artifacts using @actions/download-artifact
